server:
  port: 80

spring:
  cache:
    type: redis
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.106.105.240:3306/demo
  redis:
    host: 39.106.105.240
    port: 6379
  data:
    mongodb:
      host: 39.106.105.240
      port: 27017
      database: demo

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.helloworld.entity

# 打印sql
logging:
  level:
    com.example.helloworld.dao: debug



